name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r ../requirements/prod.txt
      - name: Check code style
        run: python manage.py check

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ruff
        run: pip install ruff
      - name: Run linter
        run: ruff check .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r ../requirements/dev.txt
      - name: Migrate database
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test
